//! Composable status line.
//!
//! The one-line ANSI string Claude Code shows (rendered by `mewxi
//! status`) is built from reorderable **blocks** instead of one hardcoded
//! format. Built-in defaults are embedded from the repo `blocks/` folder
//! (see `build.rs`); users override them by id, or add their own, by
//! dropping `*.toml` files in their `status_blocks_dir` (config). The
//! order + enabled set comes from `status_blocks` in `accounts.toml`.
//!
//! With no user config the default set reproduces the legacy line
//! byte-for-byte — see the golden tests in [`crate::watch`].

mod block;
mod command;
pub mod engine;
mod git;

pub use block::{parse_block, Block, BlockKind};

use crate::accounts::{self, Account, AccountsView};
use crate::watch::SessionMeta;
use engine::Ctx;
use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::time::Duration;

// Generated by build.rs: `pub static DEFAULT_BLOCKS: &[(&str, &str)]` of
// `(file_stem, file_contents)` for every `blocks/*.toml`.
include!(concat!(env!("OUT_DIR"), "/default_blocks.rs"));

/// Built-in composition order — the id sequence that reproduces the
/// legacy status line. Used when `accounts.toml` has no `status_blocks`.
pub const DEFAULT_ORDER: &[&str] = &[
    "hint",
    "update",
    "prefix",
    "model",
    "five_hour",
    "extra",
    "reset",
    "ctx",
    "git_dirty",
];

/// Parse the embedded default blocks into `(ordered default ids, by-id
/// map)`. Malformed defaults are skipped (should never happen — they're
/// shipped + tested).
fn default_block_map() -> std::collections::HashMap<String, Block> {
    let mut by_id = std::collections::HashMap::new();
    for (stem, src) in DEFAULT_BLOCKS {
        if let Ok(b) = parse_block(stem, src) {
            by_id.insert(b.id.clone(), b);
        }
    }
    by_id
}

/// Read + parse every `*.toml` in `dir` (sorted). Returns blocks in file
/// order. Missing dir → empty. Malformed files are skipped.
fn user_blocks(dir: &Path) -> Vec<Block> {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut paths: Vec<PathBuf> = entries
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|s| s.to_str()) == Some("toml"))
        .collect();
    paths.sort();
    let mut out = Vec::new();
    for path in paths {
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let Ok(src) = std::fs::read_to_string(&path) else {
            continue;
        };
        if let Ok(b) = parse_block(stem, &src) {
            out.push(b);
        }
    }
    out
}

/// The effective, ordered, *enabled* block set for `view`: embedded
/// defaults overlaid by user-dir blocks (by id), ordered per
/// `status_blocks` (or [`DEFAULT_ORDER`] when unset).
///
/// When `status_blocks` is set it is the source of truth for which
/// *default* blocks render — defaults left out of the list stay hidden
/// (they remain visible in the composer so they can be re-added). Only
/// freshly-dropped *user* blocks not yet in the list are appended, so a
/// new custom `.toml` surfaces without a config edit. With no
/// `status_blocks`, the built-in [`DEFAULT_ORDER`] (plus any user blocks)
/// is used and renders byte-for-byte identically to the legacy line.
pub fn load_blocks(view: &AccountsView) -> Vec<Block> {
    let mut by_id = default_block_map();
    let mut user_ids: Vec<String> = Vec::new();

    let dir = view
        .status_blocks_dir
        .clone()
        .or_else(accounts::default_status_blocks_dir);
    if let Some(dir) = dir {
        for b in user_blocks(&dir) {
            if !by_id.contains_key(&b.id) {
                user_ids.push(b.id.clone());
            }
            by_id.insert(b.id.clone(), b); // user wins by id
        }
    }

    let mut ordered: Vec<Block> = Vec::new();
    match &view.status_blocks {
        Some(order) => {
            let mentioned: HashSet<&str> = order.iter().map(|(id, _)| id.as_str()).collect();
            for (id, enabled) in order {
                if *enabled {
                    if let Some(b) = by_id.get(id) {
                        ordered.push(b.clone());
                    }
                }
            }
            // Append only freshly-dropped *user* blocks not yet listed, so
            // a new custom file surfaces without a config edit. Defaults
            // left out of `status_blocks` stay hidden (curated by the user).
            for id in &user_ids {
                if !mentioned.contains(id.as_str()) {
                    if let Some(b) = by_id.get(id) {
                        ordered.push(b.clone());
                    }
                }
            }
        }
        None => {
            for id in DEFAULT_ORDER {
                if let Some(b) = by_id.get(*id) {
                    ordered.push(b.clone());
                }
            }
            for id in &user_ids {
                if let Some(b) = by_id.get(id) {
                    ordered.push(b.clone());
                }
            }
        }
    }
    ordered
}

/// Every block id known to `view` (defaults + user dir), with whether
/// each is a built-in default. Used by the TUI composer's "add" palette.
pub fn known_blocks(view: &AccountsView) -> Vec<(Block, bool)> {
    let defaults = default_block_map();
    let mut seen: HashSet<String> = HashSet::new();
    let mut out: Vec<(Block, bool)> = Vec::new();
    // Defaults first, in canonical order.
    for id in DEFAULT_ORDER {
        if let Some(b) = defaults.get(*id) {
            seen.insert(b.id.clone());
            out.push((b.clone(), true));
        }
    }
    // Then user-dir blocks (overrides keep the default's "builtin" flag
    // for the id; brand-new ids are user blocks).
    let dir = view
        .status_blocks_dir
        .clone()
        .or_else(accounts::default_status_blocks_dir);
    if let Some(dir) = dir {
        for b in user_blocks(&dir) {
            let is_builtin = defaults.contains_key(&b.id);
            if seen.insert(b.id.clone()) {
                out.push((b, is_builtin));
            }
        }
    }
    out
}

/// All known blocks for the composer, in display order, each tagged with
/// `(enabled, is_builtin)`. Like [`load_blocks`] but keeps *disabled*
/// blocks (so the composer can re-enable them) and never executes
/// commands. Saved-order first, then any newly-discovered blocks.
pub fn composer_rows(view: &AccountsView) -> Vec<(Block, bool, bool)> {
    let known = known_blocks(view); // (Block, is_builtin), defaults-first then user
    let builtin: std::collections::HashMap<String, bool> =
        known.iter().map(|(b, bi)| (b.id.clone(), *bi)).collect();
    let by_id: std::collections::HashMap<String, Block> =
        known.iter().map(|(b, _)| (b.id.clone(), b.clone())).collect();

    let mut out: Vec<(Block, bool, bool)> = Vec::new();
    let mut placed: HashSet<String> = HashSet::new();
    if let Some(order) = &view.status_blocks {
        for (id, enabled) in order {
            if let Some(b) = by_id.get(id) {
                out.push((b.clone(), *enabled, *builtin.get(id).unwrap_or(&false)));
                placed.insert(id.clone());
            }
        }
    }
    // Newly-discovered blocks (or all of them, when no saved order) come
    // last, enabled by default so they surface.
    for (b, bi) in &known {
        if !placed.contains(&b.id) {
            out.push((b.clone(), true, *bi));
            placed.insert(b.id.clone());
        }
    }
    out
}

/// Raw embedded TOML for a built-in block id (used to seed a user-dir
/// override when the composer first deep-edits a built-in block).
pub fn default_block_source(id: &str) -> Option<&'static str> {
    DEFAULT_BLOCKS
        .iter()
        .find(|(stem, _)| *stem == id)
        .map(|(_, src)| *src)
}

/// A commented skeleton for a brand-new user block, with the id filled in.
pub fn new_block_skeleton(id: &str) -> String {
    format!(
        "# Status-line block. Edit `template`, or set `type = \"command\"`\n\
         # to run a shell command and show its output.\n\
         #\n\
         # Fields: {{account}} {{model}} {{think}} {{five_h_segment}} {{reset_segment}}\n\
         #         {{ctx_pct}} {{ctx_cur}} {{ctx_cap}} {{extra_pct}} {{extra_amounts}}\n\
         #         {{update_segment}} {{hint_segment}} {{git_dirty}}\n\
         # Colors: <cyan> <grey> <yellow> <magenta> <red> <green> <blue> <white>\n\
         # when:   always · multi_account · model_present · five_h_visible · billing_extra\n\
         #         reset_present · ctx_present · update_available · setup_incomplete · git_repo\n\
         #         (prefix with ! to negate, e.g. when = \"!billing_extra\")\n\
         label = \"{id}\"\n\
         when = \"always\"\n\
         template = \"<cyan>{id}</cyan> \"\n"
    )
}

/// A representative render context with fixed sample values, used by the
/// TUI composer's live preview so every common block shows regardless of
/// real usage. `billing_extra = false` (the normal case), so the 5h meter
/// previews rather than the extra-usage meter.
pub fn preview_ctx() -> Ctx {
    let mut f: std::collections::HashMap<&'static str, String> = std::collections::HashMap::new();
    f.insert(
        "hint_segment",
        "\x1b[33m⚠ mewxi: setup incomplete — open mewxi\x1b[0m \x1b[90m|\x1b[0m ".into(),
    );
    f.insert(
        "update_segment",
        "\x1b[35m↑ mewxi update v1.4.0\x1b[0m \x1b[90m|\x1b[0m ".into(),
    );
    f.insert("account", "priv".into());
    f.insert("model", "Opus 4.8".into());
    f.insert("think", " \x1b[90m·\x1b[0m \x1b[35mthink:high\x1b[0m".into());
    f.insert(
        "five_h_segment",
        "\x1b[36m5h\x1b[0m \x1b[32m12.3%\x1b[0m \x1b[90m(live)\x1b[0m".into(),
    );
    f.insert(
        "reset_segment",
        " \x1b[90m→\x1b[0m reset \x1b[33m14:30\x1b[0m \x1b[90m(42m)\x1b[0m".into(),
    );
    f.insert("ctx_pct", "\x1b[32m45%\x1b[0m".into());
    f.insert("ctx_cur", "90k".into());
    f.insert("ctx_cap", "200k".into());
    f.insert("git_dirty", "3".into());
    Ctx::from_parts(true, false, f)
}

/// Render `blocks` in order against `ctx`, concatenated with an empty
/// joiner (each default block bakes in its own separators).
pub fn render_blocks(ctx: &Ctx, blocks: &[Block]) -> String {
    let mut out = String::new();
    for b in blocks {
        out.push_str(&render_one(ctx, b));
    }
    out
}

fn render_one(ctx: &Ctx, block: &Block) -> String {
    match &block.kind {
        BlockKind::Template { when, template } => {
            engine::render_template_block(ctx, when, template)
        }
        BlockKind::Command {
            when,
            command,
            color,
            timeout_ms,
        } => {
            if !ctx.eval_when(when) {
                return String::new();
            }
            command::run_command_block(
                command,
                Duration::from_millis(*timeout_ms),
                color.as_deref(),
            )
        }
    }
}

/// Compose the full status line for `account`. Loads the block set from
/// config, builds the render context (fetching aggregate + live usage),
/// and concatenates the rendered blocks. This is the body of the legacy
/// `watch::render_status_for_account`.
pub fn compose(
    account: &Account,
    multi_account: bool,
    transcript: Option<&Path>,
    meta: SessionMeta<'_>,
    no_live: bool,
) -> String {
    let blocks = match accounts::load_accounts() {
        Ok(view) => load_blocks(&view),
        Err(_) => default_order_blocks(),
    };
    let ctx = Ctx::build(account, multi_account, transcript, meta, no_live);
    render_blocks(&ctx, &blocks)
}

/// Fallback block set (embedded defaults in [`DEFAULT_ORDER`]) when the
/// config can't be read.
fn default_order_blocks() -> Vec<Block> {
    let by_id = default_block_map();
    DEFAULT_ORDER
        .iter()
        .filter_map(|id| by_id.get(*id).cloned())
        .collect()
}

/// Compose using only the embedded defaults (in [`DEFAULT_ORDER`]) from
/// already-loaded data. The golden byte-identity tests in
/// [`crate::watch`] compare this against `watch::render_status_legacy`.
#[cfg(test)]
pub(crate) fn compose_default_from_data(
    account: &Account,
    multi_account: bool,
    transcript: Option<&Path>,
    meta: SessionMeta<'_>,
    agg: &crate::stats::Aggregate,
    live: Option<&crate::live_usage::LiveUsage>,
) -> String {
    let ctx = Ctx::from_data(account, multi_account, transcript, meta, agg, live);
    render_blocks(&ctx, &default_order_blocks())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn view(
        status_blocks: Option<Vec<(String, bool)>>,
        dir: std::path::PathBuf,
    ) -> AccountsView {
        AccountsView {
            accounts: vec![],
            ignored: vec![],
            default_account: None,
            default_new_session_dir: None,
            defocus_input_after_send: true,
            default_view: None,
            update_channel: None,
            update_check: true,
            update_interval: None,
            update_prompt: true,
            update_repo_dir: None,
            update_build_dir: None,
            subagent_tool_action: false,
            status_blocks_dir: Some(dir),
            status_blocks,
        }
    }

    fn ids(blocks: Vec<Block>) -> Vec<String> {
        blocks.into_iter().map(|b| b.id).collect()
    }

    #[test]
    fn embedded_defaults_parse_and_cover_order() {
        let by_id = default_block_map();
        for id in DEFAULT_ORDER {
            assert!(by_id.contains_key(*id), "missing default block '{id}'");
        }
        assert_eq!(by_id.len(), DEFAULT_ORDER.len());
    }

    #[test]
    fn no_config_uses_default_order() {
        let tmp = tempfile::TempDir::new().unwrap();
        let v = view(None, tmp.path().to_path_buf());
        assert_eq!(
            ids(load_blocks(&v)),
            DEFAULT_ORDER.iter().map(|s| s.to_string()).collect::<Vec<_>>()
        );
    }

    #[test]
    fn explicit_order_hides_unlisted_and_disabled() {
        let tmp = tempfile::TempDir::new().unwrap();
        // model enabled, ctx listed-but-disabled, everything else unlisted.
        let v = view(
            Some(vec![("model".into(), true), ("ctx".into(), false)]),
            tmp.path().to_path_buf(),
        );
        assert_eq!(ids(load_blocks(&v)), vec!["model".to_string()]);
    }

    #[test]
    fn dropped_user_block_is_appended() {
        let tmp = tempfile::TempDir::new().unwrap();
        std::fs::write(
            tmp.path().join("git.toml"),
            "type = \"command\"\ncommand = \"echo x\"\n",
        )
        .unwrap();
        let v = view(Some(vec![("model".into(), true)]), tmp.path().to_path_buf());
        // model (listed) then git (freshly-dropped user block, appended).
        assert_eq!(ids(load_blocks(&v)), vec!["model".to_string(), "git".to_string()]);
    }

    #[test]
    fn user_dir_overrides_default_by_id() {
        let tmp = tempfile::TempDir::new().unwrap();
        std::fs::write(
            tmp.path().join("ctx.toml"),
            "label = \"my ctx\"\ntemplate = \"CTX\"\n",
        )
        .unwrap();
        let v = view(None, tmp.path().to_path_buf());
        let blocks = load_blocks(&v);
        let ctx = blocks.iter().find(|b| b.id == "ctx").unwrap();
        assert_eq!(ctx.label, "my ctx"); // user file won by id
    }
}
